---
title: "R Notebook"
output: html_notebook
---

Testing upload methods for new data

```{r}
#Load packages - Ran script with some packages turned off and it work, but need to try with more
library(tidyverse)
library(janitor) #Where do I use this? Test running without - removing empty rows/NArows
library(hutils) #Used to drop empty columns 
library(obistools) #Used for initial species matches to WoRMs - good for cleaning taxonomic names
library(worrms) #Used to derive accepted names and taxonomic hierarchies
library(curl) #??? Test running without.
library(stringr) #Used to remove white-space after 
library(here)
```

```{r}
#Uploading data with no headers as header information spread over multiple rows - goal is go get date as header
micro20 <- read.csv(here("upload_2020.csv"), na.strings = c("","NA"))

#removing empty rows and columns 
micro20 <- micro20 %>% 
  janitor::remove_empty()

#Rename first column as species as contains species information
micro20 <- micro20 %>% 
  rename(species = ï..species)

#List of Louis group names to associate with each species (right now group names at top of row of species)
group_name <- c("Bacillariophyta", "Chlorophyta-Prasinophyta" , 
                "Choanoflagellata", "Chrysophyta", "Ciliophora", "Cryptophyta", 
                "Cyanobacteria", "Dictyochophyta", "Dinoflagellata", "Ebriidea",
                "Euglenophyta", "Kinetoplastidea", "Metazoa", "Protozoa",
                "Prymnesiophyta-Haptophyta", "Raphidiophyta", 
                "Unknown very small flagellated species",
                "Unknown very small non-flagellated cells", "Unknown cells",
                "Notes") %>% 
  str_c(collapse = "|")

#Searching group names and adding to new column to the left of species
micro20 <- micro20 %>% 
  mutate(group = str_match(species, group_name)) %>% 
  relocate(group, .after = species)

#Filling down the group names so each species is associated with group - problem is I need to get rid of the original group name above the species within the group
micro20 <- micro20 %>% 
  fill(group)

#Needs to separate and deal with notes before I can remove group names from species

#Separating notes for re-introduction later - if needed.
notes <- micro20 %>% 
  filter(group == "Notes") %>%
  janitor::remove_empty() %>% 
  mutate(id = row_number()) %>% 
  unite("note_num", group, id, sep = "_") %>% 
  select(!species) 

notes <- setNames(data.frame(t(notes[ , -1])), notes [ , 1])

notes <- notes %>% 
  rownames_to_column("id") %>% 
  unite("analyst_note", Notes_1:Notes_5, sep = " ", na.rm = TRUE)


#Removing notes and then any rows that only have NAs for abundance counts - This gets rid of the group row that I placed into its own column. I'm not 100% sure if this is working properly. I could also remove these later after I have transformed to species being columns. Go with it for now. Could also just explicity filter out the names - safer, but less adaptable.
micro20 <- micro20 %>% 
  filter(!group == "Notes") %>% 
  filter_at(vars(QPHY1328:QPHY1369), any_vars(!is.na(.)))

#Need to unite the random qualifiers in the X.1 column with the species column
micro20 <- micro20 %>% 
  unite("species", species, X.1, sep = " ", na.rm = TRUE)


#Finding taxonomic informatio containing unknown and unidentified. When uploading new data, check that this captures all rows without taxonomic designations. If not add new terms to code below.
unknown <- micro20 %>% 
  filter(str_detect(species, "Unknown") |
         str_detect(species, "Unidentified") |
         str_detect(species, "Resting"))

#Renaming unknown and unidentified taxonomic designations. When uploading new data, check that all rows with unknown designations have been captured and fixed.  If not, add terms to the code below. I do this work here, because I can use Louis' groupings to help guide the new names. Unidentified diatoms are not dealt with here -  fixed later when data transposed and then size groups are summed and the new column is renamed. I wonder as I incorporate new sheets and add new searches, will this just become more encompassing? Can I use it if not all things in list/code are found - seems so, see bottom search?
unknown <- unknown %>% 
  mutate(species_fix = case_when(species == "Unknown forms" &
                             group == "Bacillariophyta" ~
                               "Bacillariophyceae",
                             species == "Unknown species" &
                             group == "Chlorophyta-Prasinophyta" ~
                               "Protozoa (alpha-starch, Chlorophyta?)",
                             species == "Unknown species" &
                             group == "Choanoflagellata" ~
                                "Choanozoa",
                             species == "Unknown species" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae",
                             species == "Resting stages" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae (resting stages)",
                             species == "Unknown very small species (dino??)" &
                             group == "Dinoflagellata" ~
                               "Protozoa (equatorial groove, Dinophyceae?)",
                             species == "Unknown species" &
                             group == "Euglenophyta" ~
                               "Euglenozoa",
                             species == "Unknown species" &
                             group == "Kinetoplastidea" ~
                               "Kinetoplastea",
                             species == "Unknown very small flagellated species" &
                             group == "Unknown very small flagellated species" ~
                               "Protozoa",
                             species == "banana" &
                             group == "pineapple" ~
                               "Protozoa")) %>% 
  relocate(species_fix, .after = species)
                             
#Now that we know that all unknown taxonomic designations have been accounted for, we can apply the above code to the full data-set. 

micro20 <- micro20 %>% 
  mutate(species = case_when(species == "Unknown forms" &
                             group == "Bacillariophyta" ~
                               "Bacillariophyceae",
                             species == "Unknown species" &
                             group == "Chlorophyta-Prasinophyta" ~
                               "Protozoa (alpha-starch, Chlorophyta?)",
                             species == "Unknown species" &
                             group == "Choanoflagellata" ~
                                "Choanozoa",
                             species == "Unknown species" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae",
                             species == "Resting stages" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae (resting stages)",
                             species == "Unknown very small species (dino??)" &
                             group == "Dinoflagellata" ~
                               "Protozoa (equatorial groove, Dinophyceae?)",
                             species == "Unknown species" &
                             group == "Euglenophyta" ~
                               "Euglenozoa",
                             species == "Unknown species" &
                             group == "Kinetoplastidea" ~
                               "Kinetoplastea",
                             species == "Unknown very small flagellated species" &
                             group == "Unknown very small flagellated species" ~
                               "Protozoa",
                             TRUE ~ as.character (species)))

#Was thinking of doing qualifier/lifestage separations here, but really makes it tough to transpose and convert to long/tidy format, so leaving it until after converted to tidy.

#Remove total cells (diatoms), unknown cells (can't use these as not possible to assign taxonomy) and non-taxonomic information here? Previously I did this beforehand, but it's sort of easier to see them in list form here. With new data, be sure to check for new designations.
non_tax_list <- micro20 %>%
  filter(str_detect(species, "Eggs") |
         str_detect(species, "pieces") |
         str_detect(species, "Fecal") |
         str_detect(species, "ejecta") |
         str_detect(species, "Crab zoea") |
         str_detect(species, "Total Cells/L") |
         str_detect(species, "Unknown cells"))

#Remove non-taxonomic rows/designations.
micro20 <- micro20 %>%
  filter(!(str_detect(species, "Eggs") |
         str_detect(species, "pieces") |
         str_detect(species, "Fecal") |
         str_detect(species, "ejecta") |
         str_detect(species, "Crab zoea") |
         str_detect(species, "Total Cells/L") |
         str_detect(species, "Unknown cells")))

#Make additional fixes to species names -  don't want to go too crazy here, but things need to be able to be found by the WoRMs database searches. Ignoring small/large designations as they will be summed once data is transposed. 
micro20 <- micro20 %>% 
  mutate(species = str_replace(species, "Copepodids", "Copepoda (copepodites)"))


#Separate Louis group/species for tidy/long reintroduction
groups <- micro20 %>% 
  select(group, species)

#So when I do this, already I can see the problem with the unknown species - Not lining up with my last script, so need a better way to do this. Might be better to use case when (done above)
micro20_tp <- micro20 %>% 
  select(!group)

micro20_tp <- setNames(data.frame(t(micro20_tp[ , -1])), micro20_tp[ , 1])

#For some reason, my abundance counts are characters - converting to numeric
micro20_tp <- micro20_tp %>% 
  mutate_if(is.character, as.numeric)

#Pushes rownames to thier own column
#Pushes the hakaiID rownames into a column with a header.
micro20_tp <- rownames_to_column(micro20_tp, "hakai_id")

#Working to sum size class abundance counts into single groups. This is tricky, because not consistent between data outputs. Here, I had to comment out Chaetoceros spp_sum because the small designation did not occur. Not really sure how to get around this. Should have a list from the non-tranformed datasheet of anything with small/medium/large
size_list <- micro20 %>%
  filter(str_detect(species, "small") |
         str_detect(species, "medium") |
         str_detect(species, "large"))
         
micro20_tp <- micro20_tp %>% 
  rowwise() %>% 
  mutate(Biddulphiales = sum(`Unidentified centric forms`, 
                   `Unidentified very small centric forms`, na.rm = TRUE),
         Pennales = sum(`Unidentified pennate forms`,
                        `Unidentified very small pennate forms`, na.rm = TRUE),
         `Skeletonema marinoi` = sum(`S. marinoi (small cells)`,
                                    `S. marinoi (large cells)`, na.rm = TRUE),
         `Chaetoceros tenuissimus` = sum(`Chaetoceros tenuissimus (large)`,
                                         `Chaetoceros tenuissimus (small)`, 
                                         na.rm = TRUE),
         #`Chaetoceros spp_sum.` = sum(`Chaetoceros spp.`,
         #                        `Chaetoeros spp. very small`, na.rm = TRUE ),
         Oligotrichea = sum(`Elongate form`, `Oligotricious forms (large)`,
                            `Oligotricious forms (medium)`, 
                            `Oligotricious forms (small)`, na.rm = TRUE))

#Checking that the sums worked.
sum_check <- micro20_tp %>% 
  select(Biddulphiales, `Unidentified centric forms`, 
         `Unidentified very small centric forms`, Pennales, 
         `Unidentified pennate forms`, `Unidentified very small pennate forms`,
         `Skeletonema marinoi`, `S. marinoi (small cells)`,
         `S. marinoi (large cells)`, `Chaetoceros tenuissimus`, 
         `Chaetoceros tenuissimus (large)`, `Chaetoceros tenuissimus (small)`,
         #`Chaetoceros spp_sum.`, `Chaetoceros spp.`, `Chaetoeros spp. very small`,
         Oligotrichea, `Elongate form`, `Oligotricious forms (large)`,
         `Oligotricious forms (medium)`, `Oligotricious forms (small)`)

#Removing size separated columns that were summed into a single column.
micro20_tp <- micro20_tp %>% 
  select(-`Unidentified centric forms`, -`Unidentified very small centric forms`,
         -`Unidentified pennate forms`, -`Unidentified very small pennate forms`,
         -`S. marinoi (small cells)`, -`S. marinoi (large cells)`,
         -`Chaetoceros tenuissimus (large)`, -`Chaetoceros tenuissimus (small)`,
         #-`Chaetoceros spp.`, -`Chaetoeros spp. very small`, 
         -`Elongate form`, -`Oligotricious forms (large)`, 
         -`Oligotricious forms (medium)`, -`Oligotricious forms (small)`)

#Changing zeros from sum math back to NA's
micro20_tp  <- micro20_tp  %>% 
  mutate(Biddulphiales = na_if(Biddulphiales, 0),
         Pennales = na_if(Pennales, 0),
         `Skeletonema marinoi` = na_if(`Skeletonema marinoi`, 0),
         `Chaetoceros tenuissimus` = na_if(`Chaetoceros tenuissimus`, 0),
         #`Chaetoceros spp_sum.` = na_if(`Chaetoceros spp_sum.`, 0),
         Oligotrichea = na_if(Oligotrichea, 0))
```

```{r}
#Merging with metadata

#Upload metadata - update to API when possible
metadata <- read_csv(here("meta_phyto_2021_04_14.csv"))

#Join with microscopy data metadata
micro20_tp <- micro20_tp %>% 
  left_join(metadata)

#reorganizing and eliminating unused columns
micro20_tp <- micro20_tp %>% 
  select(date, collected, hakai_id, line_out_depth, work_area, site_id,
         lat, long, volume, lugols, collected,
         `Achnanthes spp.`:Oligotrichea)

#Find rows where there was no metadata match - Check to ensure out is 0, which means all of the data was merged.
meta_missing <- micro20_tp %>%
  filter(is.na(collected))
```

```{r}
#Convert data to tidy

#Making data Tidy 
micro_tidy <- micro20_tp %>% 
  pivot_longer(c(`Achnanthes spp.`: Oligotrichea),
               names_to = "species", values_to = "counts")

#Drop NAs - species not observed.
micro_tidy <- micro_tidy %>%
  drop_na(counts)
```

```{r}
#Trying to re-add Louis' group designations
micro_tidy <- micro_tidy %>% 
  left_join(groups) %>% 
  relocate(.before = species )

#Works with exception to columns I summed/changed. I guess I can just manually re-add here.


```



```{r}
#Further cleaning of data not done before making the data tidy - was too complicated with having to transpose the data for merging with metadata.


#For the below regex string search lists, make sure to look at the original data to ensure all qualifiers/lifestages have been accounted for.

#This creates regex list that will be used to add these terms to lifeStage column.
lifeStage_regex <- c("resting stages", "resting stage", "r\\.s", 
                     "nauplii/ekdysis", "\\bspore", "Auxospore", 
                     "copepodites") %>% 
  str_c(collapse = "|")

#This creates regex list that will be used to add these terms to the identificationRemark column. 
identificationRemark_regex <- c("alpha-starch, Chlorophyta\\?",
                                "equatorial groove, Dinophyceae\\?",
                                "cinctus/radicans") %>% 
  str_c(collapse = "|")

#This creates regex list that will be used to add these terms to the identificationQualifier column. I could likely make the search easier and eliminate [:blank:]spp$ by using stringr::str_trim to remove whitespace before or after.
identificationQ_regex <- c("[:blank:]spp$", "spp\\.", "sp\\.") %>% 
  str_c(collapse = "|")

#This step uses the regular expression lists defined above to find matches within the taxonomic column and for these matches, writes the specified terms to either lifeStage, indentificationQualifier or identificationRemark columns.
micro_tidy <- micro_tidy %>%
  mutate(lifeStage = str_match(species, lifeStage_regex)) %>%
  mutate(identificationQualifier = str_match(species, identificationQ_regex)) %>%
  mutate(identificationRemark = str_match(species, identificationRemark_regex))

# Rename lifeStage terms to match accepted vocabulary and fix a weird identificationQualifier spp that has white space making regex work difficult. 
micro_tidy <- micro_tidy %>% 
  mutate(lifeStage = str_replace(lifeStage, "spore", "spores")) %>%  
  mutate(lifeStage = str_replace(lifeStage, "resting stages", "resting spores")) %>% 
  mutate(lifeStage = str_replace(lifeStage, "resting stage", "resting spores")) %>%  
  mutate(lifeStage = str_replace(lifeStage, "r\\.s", "resting spores")) %>% 
  mutate(lifeStage = str_replace(lifeStage, "nauplii/ekdysis", "nauplii")) %>% 
  mutate(identificationQualifier = str_replace(identificationQualifier,
                                                "[:blank:]spp$", "spp."))

#Adding spp. where I moved cinctus/radicans to identificationRemark. The last term in the case_when function makes sure that the other identificationQualifiers are not overwritten. Cinctus/Radicans not included in all sheets, but doesn't matter, can be run anyways so it is picked up when run.
micro_tidy <- micro_tidy %>% 
  mutate(identificationQualifier = case_when(identificationRemark == 
                                               "cinctus/radicans" ~ "spp.",
                                             TRUE ~ as.character
                                             (identificationQualifier)))

#Make IdentificationQualifiers more encompassing
micro_tidy <- micro_tidy %>% 
  mutate(identificationRemark = str_replace(identificationRemark,
                                            "alpha-starch, Chlorophyta\\?", 
"Cells too small to identify. Stained blue indicating alpha starch and could be Chlorophyta"))

#Unknown protozoa that could be Dinophyceae
micro_tidy <- micro_tidy %>% 
  mutate(identificationRemark = str_replace(identificationRemark,
                                            "equatorial groove, Dinophyceae\\?", 
"Cells too small to identify. Showed equatorial groove and could be Dinophyceae"))

#Couldn't tell between resting stage cinctus and radicans
micro_tidy <- micro_tidy %>% 
  mutate(identificationRemark = str_replace(identificationRemark,
                                            "cinctus/radicans", 
"Unable to distinguish between Chaetoceros cinctus and radicans"))

#Adding reason why classification was stopped at sp., spp according to Horten et al. In theory, shouldn't this Qualifier be put on any occurrence that stops before species level? Based on figure 1 in Horten et al., I think that the qualifier should be added even when there is no sp. or spp. I will add this after the taxonomic hierarchy has been applied so that I can filter for it.
micro_tidy <- micro_tidy %>% 
  mutate(identificationQualifier = case_when(identificationQualifier == 
                                               "spp." ~ "spp. Indet.",
                                             identificationQualifier ==
                                               "sp." ~ "sp. Indet.",
                                             TRUE ~ as.character
                                             (identificationQualifier)))

#This step is time consuming to run, but removes any white-space before/after strings created through regex work.
micro_tidy <- micro_tidy %>% 
  mutate(species = stringr::str_trim(species, side = "right"))
```

```{r}
#Remove any identifiers from the species designations in the species column - make sure to update if the data has new identifiers/qualifiers/lifestages etc.
micro_tidy <- micro_tidy %>% 
  mutate(species = str_replace(species, "\\(resting stages\\)", "")) %>% 
  mutate(species = str_replace(species, "resting stage", "")) %>%
  mutate(species = str_replace(species, "resting stages", "")) %>%
  mutate(species = str_replace(species, "r\\.s", "")) %>%
  mutate(species = str_replace(species, "Auxospore", "")) %>%
  mutate(species = str_replace(species, "\\(copepodites\\)", "")) %>%
  mutate(species = str_replace(species, "\\(nauplii/ekdysis\\)", "")) %>%
  mutate(species = str_replace(species, "nauplii/ekdysis", "")) %>%
  mutate(species = str_replace(species, "spp\\.", "")) %>%
  mutate(species = str_replace(species, "\\bspp", "")) %>%
  mutate(species = str_replace(species, "sp\\.", "")) %>%
  mutate(species = str_replace(species, "spore forms", "")) %>% 
  mutate(species = str_replace(species, "cinctus/radicans", "")) %>%
  mutate(species = str_replace(species, "\\(elongate form\\)", "")) %>% 
  mutate(species = str_replace(species, "Pterosperma  s", "Pterosperma")) %>% 
  mutate(species = str_replace(species, "\\(equatorial groove, Dinophyceae\\?\\)","")) %>%
  mutate(species = str_replace(species, "\\(alpha-starch, Chlorophyta\\?\\)", "")) %>% 
  mutate(species = str_replace(species, "[:blank:]spp$", ""))

```


```{r}
#These steps are crosschecks to ensure that all of the above string work was done correctly. Carefully examine the data as after this, the data are exported and then matched with the WoRMs database.

#This step/sheet is a quality check to ensure that all of the lifeStage-taxonomic combinations are present 
lifeStage_check <- micro_tidy %>% 
  distinct(across(c(species, lifeStage))) %>% 
  filter(!is.na(lifeStage)) 

#Check that all the identificationQualifier combinations are present
identificationQ_check <- micro_tidy %>% 
  distinct(across(c(species, identificationQualifier))) %>% 
  filter(!is.na(identificationQualifier)) 

#Check that all of the identificationRemark combinations are present
identificationRemark_check <- micro_tidy %>% 
  distinct(across(c(species, identificationRemark))) %>% 
  filter(!is.na(identificationRemark)) 

micro_distinct <- micro_tidy %>%
  distinct(species, lifeStage, identificationQualifier, identificationRemark, 
           .keep_all = TRUE)
```




