---
title: "R Notebook"
output: html_notebook
---

Testing upload methods for new data - Unfortunately, changes need to be made for each new data sheet. I'm conflicted as to whether some of these changes could be done more quickly manually within excel.

```{r}
#Load packages - Ran script with some packages turned off and it work, but need to try with more
library(tidyverse)
library(janitor) #Where do I use this? Test running without - removing empty rows/NArows
library(hutils) #Used to drop empty columns 
library(obistools) #Used for initial species matches to WoRMs - good for cleaning taxonomic names
library(worrms) #Used to derive accepted names and taxonomic hierarchies
library(curl) #??? Test running without.
library(stringr) #Used to remove white-space after 
library(here)
library(readxl)
```

```{r}
#Uploading data with no headers as header information spread over multiple rows - goal is go get HakaiID as header. Better to use read_csv, but doesn't work for transpose stage later as I have it set for a data frame, not tibble. Will fix, but works as it is for now.
micro <- read_xlsx(here("files", "Calvert_phyto.xlsx"), sheet = "KC10_3")

#Thinks this works - replaces read.csv commented out above. Caused errors in Notes DF
#micro <- read_csv(here("upload_2020.csv"), na = "")

#removing empty rows and columns 
micro <- micro %>% 
  janitor::remove_empty()

#Rename first column as species as contains species information
# micro <- micro %>%
#   rename(species = ï..species)

#This dataset was pre-formatted - renaming group column
# micro <- micro %>% 
#   rename(group = X)
```


```{r}
#Commented out here because group was already pre-formatted for this sheet.

#List of Louis group names to associate with each species (right now group names in species list above species names with those groups) - list needs to be updated if there are differences or new groups added - hopefully encompassing eventually, but use caution as Louis makes small changes regularily.
group_name <- c("Bacillariophyta", "Chlorophyta-Prasinophyta" , "Chlorophyta",
                "Choanoflagellata", "Chrysophyta", "Ciliophora", "Cryptophyta",
                "Cyanobacteria", "Dictyophyta", "Dictyochophyta", "Dinoflagellata", "Ebriidea",
                "Euglenophyta", "Kinetoplastidea", "Metazoa", "Protozoa", "Haptophyta",
                "Prymnesiophyta-Haptophyta", "Raphidiophyta",
                "Unknown very small flagellated species",
                "Unknown very small non-flagellated cells", "Unknown cells",
                "Unknown flagellae-bearing cells",
                "Notes") %>%
  str_c(collapse = "|")

#Searching group names and adding to new column to the left of species - after this step, check to see that new column with group names match with those in the species column
micro <- micro %>%
  mutate(group = str_match(species, group_name)) %>%
  relocate(group, .after = species)

#Filling down the group names so each species is associated with a group 
micro <- micro %>%
  fill(group)


#Changes captured in next script where data is bound and distinct combinations examined
micro <- micro %>% 
  mutate(group = case_when(group == "Chlorophyta" ~ "Chlorophyta-Prasinophyta",
                           group == "Haptophyta" ~ "Prymnesiophyta-Haptophyta",
                           group == "Dictyophyta" ~ "Dictyochophyta",
                           TRUE ~ as.character (group)))

micro <- micro %>% 
  mutate(group = case_when(species == "Chrysochromulina spp" ~ "Prymnesiophyta-Haptophyta",
                           TRUE ~ as.character (group)))

micro <- micro %>% 
  mutate(species = case_when(species == "Phaeocystis pouchetii" ~ "Phaeocystis poucheteii",
                             TRUE ~ as.character (species)))
```


```{r}
#commented out because there was no notes on the pre-formatted sheet.

#Dealing with analyst notes

#Need to separate and deal with notes before further work can be done - want to save and possibly reincorporate notes.

#Separating notes for re-introduction later - if needed.
notes <- micro %>%
  filter(group == "Notes") %>%
  janitor::remove_empty() %>%
  mutate(id = row_number()) %>%
  unite("note_num", group, id, sep = "_") %>%
  select(!species)

notes <- as.data.frame(notes)

notes <- setNames(data.frame(t(notes[ , -1])), notes [ , 1])

#With different sheets this will fail as they have different numbers of notes - will need to look at notes datasheet and see how many Notes_1, Notes_2 columns there are.

notes <- notes %>%
  rownames_to_column("id") %>%
  unite("analyst_note", Notes_1:Notes_4, sep = " ", na.rm = TRUE)

#No notes

```


```{r}
#Removing notes and then any rows that only have NAs for abundance counts - Needs to be changed to reflect Hakai IDs (columns) - Update with new data.

micro <- micro %>% 
  filter(!group == "Notes") %>%
  filter_at(vars(CPHY521:CPHY540), any_vars(!is.na(.)))

#Unite the random qualifiers (eg. sp., non motile) that are placed in the X and X.1 columns. Again, these columns need to be checked with each new upload to be reflective of data.
micro <- micro %>%
  unite("species", species, `...3`, sep = " ", na.rm = TRUE)
```


```{r}
#Renaming and/or removing unknown species.

#Finding taxonomic information currently combined with the species names containing unknown and unidentified. When uploading new data, check that this captures all rows without taxonomic designations. If not add new terms to code in next step.
unknown <- micro %>% 
  filter(str_detect(species, "Unknown") |
         str_detect(species, "Unidentified") |
         str_detect(species, "Resting"))

#Renaming unknown and unidentified taxonomic designations. When uploading new data, check that all rows with unknown designations have been captured and fixed.  If not, add terms to the code below. I do this work here, because I can use Louis' groupings to help guide the new names. Note, unidentified diatoms with size designations are not dealt with her, so species_fix will show NAs.  Fixed later when data transposed and then size groups are summed and the new column is renamed. Unknown cells/non-flagellated cells also not dealt with as data are not carried forward (species_fix will show NA, these data removed later). This list/fixes can grow and include terms not included in the datasheet and will still work - become more encompassing, but be sure to cross-check

#Update for Chrysophyta (make Chrysophyceae) and Raphidophyta

unknown <- unknown %>% 
  mutate(species_fix = case_when(species == "Unknown forms" &
                             group == "Bacillariophyta" ~
                               "Bacillariophyceae",
                             species == "Unknown species" &
                             group == "Chlorophyta-Prasinophyta" ~
                               "Protozoa (alpha-starch, Chlorophyta?)",
                             species == "Unknown species" &
                             group == "Chlorophyta" ~
                               "Protozoa (alpha-starch, Chlorophyta?)",
                             species == "Unknown species" &
                             group == "Choanoflagellata" ~
                                "Choanozoa",
                             species == "Unknown species" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae",
                             species == "Resting stages" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae (resting stages)",
                             species == "Unknown very small species (dino??)" &
                             group == "Dinoflagellata" ~
                               "Protozoa (equatorial groove, Dinophyceae?)",
                             species == "Unknown species" &
                             group == "Euglenophyta" ~
                               "Euglenozoa",
                             species == "Unknown species" &
                             group == "Kinetoplastidea" ~
                               "Kinetoplastea",
                             species == "Unknown very small flagellated species" &
                             group == "Unknown very small flagellated species" ~
                               "Protozoa",
                             species == "Unknown flagellae-bearing cells" &
                             group == "Unknown flagellae-bearing cells" ~
                               "Protozoa",
                             species == "Unknown species" &
                             group == "Chrysophyta" ~
                               "Chrysophyceae",
                             species == "banana" &
                             group == "pineapple" ~
                               "Protozoa")) %>% 
  relocate(species_fix, .after = species)
                             
#Now that we know that all unknown taxonomic designations have been accounted for, we can apply the above code to the full data-set. If there are changes, make sure to bring the above list down to be applied to the full dataset.

micro <- micro %>% 
  mutate(species = case_when(species == "Unknown forms" &
                             group == "Bacillariophyta" ~
                               "Bacillariophyceae",
                             species == "Unknown species" &
                             group == "Chlorophyta-Prasinophyta" ~
                               "Protozoa (alpha-starch, Chlorophyta?)",
                             species == "Unknown species" &
                             group == "Chlorophyta" ~
                               "Protozoa (alpha-starch, Chlorophyta?)",
                             species == "Unknown species" &
                             group == "Choanoflagellata" ~
                                "Choanozoa",
                             species == "Unknown species" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae",
                             species == "Resting stages" &
                             group == "Dinoflagellata" ~
                               "Dinophyceae (resting stages)",
                             species == "Unknown very small species (dino??)" &
                             group == "Dinoflagellata" ~
                               "Protozoa (equatorial groove, Dinophyceae?)",
                             species == "Unknown species" &
                             group == "Euglenophyta" ~
                               "Euglenozoa",
                             species == "Unknown species" &
                             group == "Kinetoplastidea" ~
                               "Kinetoplastea",
                             species == "Unknown very small flagellated species" &
                             group == "Unknown very small flagellated species" ~
                               "Protozoa",
                             species == "Unknown flagellae-bearing cells" &
                             group == "Unknown flagellae-bearing cells" ~
                               "Protozoa",
                             species == "Unknown species" &
                             group == "Chrysophyta" ~
                               "Chrysophyceae",
                             species == "banana" &
                             group == "pineapple" ~
                               "Protozoa",
                             TRUE ~ as.character (species)))

#Was thinking of doing qualifier/lifestage separations here, but really makes it tough to transpose and convert to long/tidy format, so leaving it until after converted to tidy.

#Remove total cells (diatoms), unknown cells (can't use these as not possible to assign taxonomy) and non-taxonomic information.With new data, be sure to look down species list and check for new terms.
non_tax_list <- micro %>%
  filter(str_detect(species, "Eggs") |
         str_detect(species, "pieces") |
         str_detect(species, "Fecal") |
         str_detect(species, "ejecta") |
         str_detect(species, "Crab zoea") |
         str_detect(species, "Total Cells/L") |
         str_detect(species, "Unknown cells") |
         str_detect(species, "Unknown very small non-flagellated cells"))

#Remove non-taxonomic rows/designations.
micro <- micro %>%
  filter(!(str_detect(species, "Eggs") |
         str_detect(species, "pieces") |
         str_detect(species, "Fecal") |
         str_detect(species, "ejecta") |
         str_detect(species, "Crab zoea") |
         str_detect(species, "Total Cells/L") |
         str_detect(species, "Unknown cells") |
         str_detect(species, "Unknown very small non-flagellated cells")))
```


```{r}
#Make additional fixes to species names -  don't want to go too crazy here, but things need to be able to be found by the WoRMs database searches. If database search doesn't find something, can come back here and fix. Ignoring small/large designations as they will be summed and then name of new column set once data is transposed with species in column format.
micro <- micro %>% 
  mutate(species = str_replace(species, "Copepodids", "Copepoda (copepodites)"))

micro <- micro %>% 
   mutate(species = str_replace(species, "Copepod nauplii/ekdysis", "Copepoda (nauplii/ekdysis)"))

micro <- micro %>% 
  mutate(species = str_replace(species, "S. marinoi auxospores", "Skeletonema marinoi auxospores"))

#Won't fuzzy match Louis name for this species - need to fix here.
micro <- micro %>% 
  mutate(species = str_replace(species, "Thalassiosira nordenskioldii", "Thalassiosira nordenskioeldii"))

micro <- micro %>% 
  mutate(species = str_replace(species, "Tintinnid forms", "Tintinnina"))
```


```{r}
#Transpose the data so that the Hakai ID is a column and species names are column headers

#Separate Louis group/species for tidy/long reintroduction using a join
groups <- micro %>% 
  select(group, species)

#Creating a new datasheet to perform transpose on - remove groups column
micro_tp <- micro %>% 
  select(!group)

micro_tp <- as.data.frame(micro_tp)

micro_tp <- setNames(data.frame(t(micro_tp[ , -1])), micro_tp[ , 1])

#For some reason, my abundance counts are characters - converting to numeric - saying I have duplicate columns... which mean I have duplicate species names??? (Check)Fixed)
micro_tp <- micro_tp %>% 
  mutate_if(is.character, as.numeric)

#Protozoa twice...
micro_test <- micro %>%
  group_by(species) %>%
  summarise(dup = n())

#Pushes rownames to their own column
#Pushes the hakaiID rownames into a column with a header.
#check that the format is correct
micro_tp <- rownames_to_column(micro_tp, "hakai_id")
```


```{r}
#Working to sum size class abundance counts into single groups. This is tricky, because not consistent between data outputs. Here, I had to comment out Chaetoceros spp_sum because the small designation did not occur. Not really sure how to get around this. 


#list of species names from the non-tranformed datasheet of anything with small/medium/large designations
size_list <- micro %>%
  filter(str_detect(species, "small") |
         str_detect(species, "medium") |
         str_detect(species, "large") |
         str_detect(species, "Elongate"))
         
#Summing columns with size designation - needs to be updated to size list above - not adaptable (i.e. will fail if not reflective of datasheet), which is why certain things are commetented out
micro_tp <- micro_tp %>% 
  rowwise() %>% 
  mutate(Biddulphiales = sum(`Unidentified centric forms`,
                             `Unidentified very small centric forms`, na.rm = TRUE),
         Pennales = sum(`Unidentified pennate forms`,
                        `Unidentified very small pennate forms`, na.rm = TRUE),
         `Skeletonema marinoi` = sum(`S. marinoi (small cells)`,
                                    `S. marinoi (large cells)`, na.rm = TRUE),
         `Chaetoceros tenuissimus` = sum(`Chaetoceros tenuissimus (large)`,
                                         `Chaetoceros tenuissimus (small)`,
                                         na.rm = TRUE),
         # `Chaetoceros spp_sum.` = sum(`Chaetoceros spp.`,
         #                              `Chaetoeros spp. very small`, na.rm = TRUE ),
         Oligotrichea = sum(`Elongate form`,
                            #`Oligotricious forms (large)`,
                            `Oligotricious forms (medium)`, 
                            `Oligotricious forms (small)`, na.rm = TRUE))

#`Elongate form`,

#In this instance, there was only a large of a specific species, so using rename here.
# micro_tp <- micro_tp %>% 
#   rename(`Chaetoceros tenuissimus` = `Chaetoceros tenuissimus (large)`)

#Checking that the sums worked. Needs to be updated to reflect sums done above.
sum_check <- micro_tp %>% 
  select(Biddulphiales, `Unidentified centric forms`,
         `Unidentified very small centric forms`,
         Pennales, 
         `Unidentified pennate forms`, 
         `Unidentified very small pennate forms`,
         `Skeletonema marinoi`, 
         `S. marinoi (small cells)`,
         `S. marinoi (large cells)`, 
         `Chaetoceros tenuissimus`,
         `Chaetoceros tenuissimus (large)`,
         `Chaetoceros tenuissimus (small)`,
         # `Chaetoceros spp_sum.`, 
         # `Chaetoceros spp.`, 
         #`Chaetoeros spp. very small`,
         Oligotrichea, 
         `Elongate form`,
         # `Oligotricious forms (large)`,
         `Oligotricious forms (medium)`, 
         `Oligotricious forms (small)`)

#Removing size separated columns that were summed into a single column. Needs to be updated to reflect sums done above.
micro_tp <- micro_tp %>% 
  select(-`Unidentified centric forms`, -`Unidentified very small centric forms`,
         -`Unidentified pennate forms`, 
         -`Unidentified very small pennate forms`,
         -`S. marinoi (small cells)`, 
         -`S. marinoi (large cells)`,
         -`Chaetoceros tenuissimus (large)`,
         -`Chaetoceros tenuissimus (small)`,
         #-`Chaetoceros spp.`, 
         #-`Chaetoeros spp. very small`,
         -`Elongate form`, 
         # -`Oligotricious forms (large)`, 
         -`Oligotricious forms (medium)`, 
         -`Oligotricious forms (small)`)

#Changing zeros from sum math back to NA's
micro_tp  <- micro_tp  %>% 
  mutate(Biddulphiales = na_if(Biddulphiales, 0),
         Pennales = na_if(Pennales, 0),
         `Skeletonema marinoi` = na_if(`Skeletonema marinoi`, 0),
         `Chaetoceros tenuissimus` = na_if(`Chaetoceros tenuissimus`, 0),
         #`Chaetoceros spp_sum.` = na_if(`Chaetoceros spp_sum.`, 0),
         Oligotrichea = na_if(Oligotrichea, 0))

#Rename Cheatoceros spp_sum to Cheatoceros spp. Need to check how I did this in my original worksheet for this dataset. It was addressed.

# micro_tp <- micro_tp %>%
#   rename(`Chaetoceros tenuissimus` = `Chaetoceros tenuissimus (small)`) 
```

```{r}
#Merging with metadata

#Upload metadata - update to API when possible
metadata <- read_csv(here("meta_phyto_2021_04_14.csv"))

#Join with microscopy data metadata
micro_tp <- micro_tp %>% 
  left_join(metadata)

#reorganizing and eliminating unused columns
micro_tp <- micro_tp %>% 
  select(date, collected, hakai_id, line_out_depth, work_area, site_id,
         lat, long, volume, lugols, collected,
         `Achnanthes spp.`:Oligotrichea)

#Find rows where there was no metadata match - Check to ensure out is 0, which means all of the data was merged.
meta_missing <- micro_tp %>%
  filter(is.na(collected))
```

```{r}
#Convert data to tidy

#Making data Tidy 
micro_tidy <- micro_tp %>% 
  pivot_longer(c(`Achnanthes spp.`: Oligotrichea),
               names_to = "species", values_to = "counts")

#Drop NAs - species not observed.
micro_tidy <- micro_tidy %>%
  drop_na(counts)
```

```{r}
#Trying to re-add Louis' group designations

#Joining groups dataframe by species
micro_tidy <- micro_tidy %>% 
  left_join(groups) %>% 
  relocate(.before = species )

#Works with exception to columns I summed/changed. I guess I can just manually re-add here.
micro_tidy <- micro_tidy %>% 
  mutate(group = case_when(species == "Biddulphiales" ~ "Bacillariophyta",
                            species == "Pennales" ~ "Bacillariophyta",
                            species == "Skeletonema marinoi" ~ "Bacillariophyta",
                            species == "Chaetoceros tenuissimus" ~ "Bacillariophyta",
                            species == "Oligotrichea" ~ "Ciliophora", 
                            TRUE ~ as.character (group)))
micro_dup <- micro_tidy %>% 
  group_by(date, species, group) %>% 
  mutate(n = n()) %>% 
  ungroup()

micro_distinct <- micro_tidy %>% 
  distinct(species, group, .keep_all = TRUE)

```

```{r}
#At this point, the different sheets should be in the same format - must of the custom work should be done. The below steps are more adaptable in that as my search lists grow, they should apply to more and more sheets. Considering this, it might be worth binding data from different sheets here to minimize further sheet specific customization of code. 
```

```{r}
#Write output to open in matching workbook
write_csv(micro_tidy, here("cleaned_csv", "kc10_invoice243-244.csv"))
```


