---
title: "R Notebook"
output: html_notebook
---

Plot the time-series to check for errors and show results.

```{r}
#Load packages
library(tidyverse)
library(patchwork)
library(here)
library(readr)
```

```{r}
#Upload output from OBIS taxonomy matching/formatting
micro <- read_csv(here("output_worms_matching", "qu39_2016_2020.csv"))

micro$date <- as.Date(micro$date, "%Y-%m-%d")

test <- micro %>% 
  filter(date > "2019-01-01" & date < "2019-12-31")
```


```{r}
#Selecting pertinent columns.
micro <- micro %>% 
  select(date, group, scientificName, AphiaID, scientificName_accepted = valid_name, 
         rank, kingdom:genus, lifeStage:identificationRemark,
        count = counts)
```

```{r}
#Chaetoceros is missing Louis group - adding here but need to go back and fix in original file

micro <- micro %>% 
  mutate(group = case_when(scientificName == "Chaetoceros" ~
                             "Bacillariophyta",
                           TRUE ~ as.character(group)))

#Checking distinct group/species
micro_distinct <- micro %>% 
  distinct(group, scientificName) %>% 
  arrange(group)

#Interesting - unknown flagallete bearing and unknown very small flagellate should probably be summed/grouped in original sheets. I wonder if this is a difference between sheets or if both existed, and I didn't account for this. Only the 2020 qu39 data had any counts for this - so they would have been removed from the other sheets, but kept here. I need to fix this - although it might not be an issue, as I class it as protozoa, so wouldn't it just be grouped in the obis matching stage? Hmm need to think about this.


#making group for protozoa chlorophyta as unknown
micro_distinct_fix <- micro_distinct %>%
  mutate(group = case_when(scientificName == "Protozoa" & 
                             group == "Unknown flagellae-bearing cells" ~
                             "Unknown_flagellate",
                           scientificName == "Protozoa" & 
                             group == "Unknown very small flagellated species" ~
                             "Unknown_flagellate",
                           scientificName == "Protozoa" & 
                             group == "Dinoflagellata" ~
                             "Unknown_Dinophyceae?",
                           scientificName == "Protozoa" & 
                             group == "Chlorophyta" ~
                             "Unknown_Chlorophyta?",
                           scientificName == "Protozoa" & 
                             group == "Chlorophyta-Prasinophyta" ~
                             "Unknown_Chlorophyta?",
                           TRUE ~ as.character(group)))

micro <- micro %>%
  mutate(group = case_when(scientificName == "Protozoa" & 
                             group == "Unknown flagellae-bearing cells" ~
                             "Unknown_flagellate",
                           scientificName == "Protozoa" & 
                             group == "Unknown very small flagellated species" ~
                             "Unknown_flagellate",
                           scientificName == "Protozoa" & 
                             group == "Dinoflagellata" ~
                             "Unknown_Dinophyceae?",
                           scientificName == "Protozoa" & 
                             group == "Chlorophyta" ~
                             "Unknown_Chlorophyta?",
                           scientificName == "Protozoa" & 
                             group == "Chlorophyta-Prasinophyta" ~
                             "Unknown_Chlorophyta?",
                           TRUE ~ as.character(group)))

micro <- micro %>%
  mutate(group = case_when(group == "Chlorophyta" ~ "Chlorophyta-Prasinophyta",
                           group == "Dictyophyta" ~ "Dictyochophyta",
                           group == "Haptophyta" ~ "Prymnesiophyta-Haptophyta",
                           TRUE ~ as.character(group)))

```

```{r}
#Designating photosynthetic species - Dictyochophyta was different in one sheet and needed to be added also:
  #Prymnesiophyta-Haptophyta
  #Chlorophyta-Prasinophyta

#Actually, need to fix these things earlier as I sum groups and these differences will not let thier counts be summed.

micro <- micro %>% 
  mutate(trophicStatus = case_when(group == "Bacillariophyta" ~ "auto",
                                   group == "Chlorophyta" ~ "auto",
                                   group == "Chlorophyta-Prasinophyta" ~ "auto",
                                   group == "Choanoflagellata" ~ "hetero",
                                   group == "Chrysophyta" ~ "auto",
                                   group == "Ciliophora" ~ "hetero",
                                   group == "Cryptophyta" ~ "auto",
                                   group == "Cyanobacteria" ~ "auto",
                                   group == "Dictyophyta" ~ "auto",
                                   group == "Dictyochophyta" ~ "auto",
                                   group == "Dinoflagellata" ~ "auto",
                                   group == "Ebriidea" ~ "hetero",
                                   group == "Euglenophyta" ~ "auto",
                                   group == "Haptophyta" ~ "auto",
                                   group == "Prymnesiophyta-Haptophyta" ~ "auto",
                                   group == "Kinetoplastidea" ~ "hetero",
                                   group == "Metazoa" ~ "hetero",
                                   group == "Raphidiophyta" ~ "auto",
                                   group == "Unknown_flagellate" ~ "auto",
                                   group == "Unknown_Chlorophyta?" ~ "auto",
                                   group == "Unknown_Dinophyceae?" ~ "auto")) %>% 
  select(date, trophicStatus, group, scientificName, 
         AphiaID, scientificName_accepted:count)

trophic_check <- micro %>% 
  distinct(group, trophicStatus) %>% 
  arrange(trophicStatus)
```

```{r}
#Selecting autotrophic groups from class level specifications above. Too coarse for dinos.
micro_sum <- micro %>%
  filter(trophicStatus == "auto") %>% #select autotrophic species
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0)) #replace NAs, created by complete, with 0s
```
```{r}
#Set order or groups for plotting


micro_sum$group <- factor(micro_sum$group,
                         levels = c("Bacillariophyta", #Y
                                    "Chrysophyta", #Y
                                    "Dictyochophyta", #Y
                                    "Raphidiophyta", #Y
                                    "Dinoflagellata", #Y
                                    "Cryptophyta",#Y
                                    "Chlorophyta-Prasinophyta", #Y 
                                    "Euglenophyta", #Y
                                    "Prymnesiophyta-Haptophyta", #Y 
                                    "Cyanobacteria", #Y
                                    "Unknown_Chlorophyta?", #Y
                                    "Unknown_Dinophyceae?", #Y
                                    "Unknown_flagellate" #Y
                                    ))
```

```{r}
#Setting colour pallete for microscopy data - roughly comparable to chemtax data
color_palette_micro <- c("#ff8000", #Diatoms 
                   "#2642D5", #Chrysophytes
                   "#ff99c7", #Dicto (same color as chryso as same pig. group)
                   "#4d6600", #Raph
                   "#ff0000", #Dino
                   "#ffff00", #Crypto
                   "#00ff00", #Chloro (chloro and eugleno same colour, same pig. group)
                   "#93FFCA", #Eugleno
                   "#7d4dcc", #Hapto
                   "#000000"  #Cyano
                   )

#Set month labels for plot
month_labels_5 <- rep(c('J','F','M','A','M','J','J','A','S','O','N','D'), 5)

month_labels <- c('J','F','M','A','M','J','J','A','S','O','N','D')
```

```{r}
micro_sum %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!group == "Unknown_Chlorophyta?" &
         !group == "Unknown_Dinophyceae?" &
         !group == "Unknown_flagellate") %>% 
  ggplot(aes(x = date, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  scale_fill_manual(values = color_palette_micro) +
  # scale_x_date(breaks = c(seq(from=as.Date("2016-01-01"),
  #                             to=as.Date("2020-12-31"),by="month")),
  #              labels = month_labels_5) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Month",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25))

```
```{r}
startTime_1 <- as.Date("2016-01-01")
endTime_1 <- as.Date("2016-11-30")
startEnd_1 <- c(startTime_1, endTime_1)

p1 <- micro_sum %>% 
  filter(date > "2016-01-01" & date < "2016-12-31" &
         !group == "Unknown_Chlorophyta?" &
         !group == "Unknown_Dinophyceae?" &
         !group == "Unknown_flagellate") %>% 
  ggplot(aes(x = date, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  ylim(0, 7000000) +
  scale_fill_manual(values = color_palette_micro, labels = 
                      c("diat.", "chry.", "dict.", "raph.", "dino.", 
                        "cryp.","chlor.", "eugl.", "hapt.", "cyan.")) +
  scale_x_date(limits = startEnd_1,
                breaks = scales::date_breaks("1 month")) +
  guides(fill = guide_legend(nrow = 1)) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 11)) +
  labs(x = "Month",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank())

startTime_2 <- as.Date("2017-01-01")
endTime_2 <- as.Date("2017-11-30")
startEnd_2 <- c(startTime_2, endTime_2)

p2 <- micro_sum %>% 
  filter(date > "2017-01-01" & date < "2017-12-31" &
         !group == "Unknown_Chlorophyta?" &
         !group == "Unknown_Dinophyceae?" &
         !group == "Unknown_flagellate") %>% 
  ggplot(aes(x = date, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  ylim(0, 7000000) +
  scale_fill_manual(values = color_palette_micro) +
  scale_x_date(limits = startEnd_2,
                breaks = scales::date_breaks("1 month")) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Month",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank())

startTime_3 <- as.Date("2018-01-01")
endTime_3 <- as.Date("2018-11-30")
startEnd_3 <- c(startTime_3, endTime_3)

p3 <- micro_sum %>% 
  filter(date > "2018-01-01" & date < "2018-12-31" &
         !group == "Unknown_Chlorophyta?" &
         !group == "Unknown_Dinophyceae?" &
         !group == "Unknown_flagellate") %>% 
  ggplot(aes(x = date, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  ylim(0, 7000000) +
  scale_fill_manual(values = color_palette_micro) +
  scale_x_date(limits = startEnd_3,
                breaks = scales::date_breaks("1 month")) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(y = bquote("Abund. (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

startTime_4 <- as.Date("2019-01-01")
endTime_4 <- as.Date("2019-11-30")
startEnd_4 <- c(startTime_4, endTime_4)

p4 <- micro_sum %>% 
  filter(date > "2019-01-01" & date < "2019-12-31" &
         !group == "Unknown_Chlorophyta?" &
         !group == "Unknown_Dinophyceae?" &
         !group == "Unknown_flagellate") %>% 
  ggplot(aes(x = date, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  ylim(0, 7000000) +
  scale_fill_manual(values = color_palette_micro) +
  scale_x_date(limits = startEnd_4,
                breaks = scales::date_breaks("1 month")) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Month",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank())

startTime_5 <- as.Date("2020-01-01")
endTime_5 <- as.Date("2020-11-30")
startEnd_5 <- c(startTime_5, endTime_5)

p5 <- micro_sum %>% 
  filter(date > "2020-01-01" & date < "2020-12-31" &
         !group == "Unknown_Chlorophyta?" &
         !group == "Unknown_Dinophyceae?" &
         !group == "Unknown_flagellate") %>% 
  ggplot(aes(x = date, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  ylim(0, 7000000) +
  scale_fill_manual(values = color_palette_micro) +
  scale_x_date(limits = startEnd_5,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Month",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank())


fig_ts <- p1/p2/p3/p4/p5

ggsave(here("figures", "qu39_ts_column.png"), fig_ts, width=16, height=15, dpi=300)
```


```{r}
#Trying to plot diatom species
p1 <- micro %>% 
  filter(group == "Bacillariophyta" & count > 10000 & !is.na(genus) &
           date > "2016-01-01" &
           date < "2016-12-31") %>% 
  group_by(date, genus) %>% 
  summarise(count_sum = sum(count)) %>% 
  ungroup() %>% 
  complete(date, genus) %>% 
  mutate(count_sum = replace_na(count_sum, 0)) %>% 
  ggplot(aes(date, count_sum, fill = genus)) +
  geom_area() +
  scale_x_date(limits = startEnd_1,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  scale_fill_brewer(palette = "Spectral",
                      name = "Genus, > 10000 cells") +
  theme_bw() +
  labs(y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(legend.position = c(0.14, 0.5),
        legend.background =  element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25)) 
  
p2 <- micro %>% 
  filter(group == "Bacillariophyta" & count > 10000 & !is.na(genus) &
           date > "2017-01-01" &
           date < "2017-12-31") %>% 
  group_by(date, genus) %>% 
  summarise(count_sum = sum(count)) %>% 
  ungroup() %>% 
  complete(date, genus) %>% 
  mutate(count_sum = replace_na(count_sum, 0)) %>% 
  ggplot(aes(date, count_sum, fill = genus)) +
  geom_area() +
  scale_x_date(limits = startEnd_2,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  scale_fill_brewer(palette = "Spectral",
                      name = "Genus, > 10000 cells") +
  theme_bw() +
  labs(y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(legend.position = c(0.14, 0.5),
        legend.background =  element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25))

p3 <- micro %>% 
  filter(group == "Bacillariophyta" & count > 10000 & !is.na(genus) &
           date > "2018-01-01" &
           date < "2018-12-31") %>% 
  group_by(date, genus) %>% 
  summarise(count_sum = sum(count)) %>% 
  ungroup() %>% 
  complete(date, genus) %>% 
  mutate(count_sum = replace_na(count_sum, 0)) %>% 
  ggplot(aes(date, count_sum, fill = genus)) +
  geom_area() +
  scale_x_date(limits = startEnd_3,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  scale_fill_brewer(palette = "Spectral",
                      name = "Genus, > 10000 cells") +
  theme_bw() +
  labs(y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(legend.position = c(0.14, 0.5),
        legend.background =  element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25))

p4 <- micro %>% 
  filter(group == "Bacillariophyta" & count > 10000 & !is.na(genus) &
           date > "2019-01-01" &
           date < "2019-12-31") %>% 
  group_by(date, genus) %>% 
  summarise(count_sum = sum(count)) %>% 
  ungroup() %>% 
  complete(date, genus) %>% 
  mutate(count_sum = replace_na(count_sum, 0)) %>% 
  ggplot(aes(date, count_sum, fill = genus)) +
  geom_area() +
  scale_x_date(limits = startEnd_4,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  scale_fill_brewer(palette = "Spectral",
                      name = "Genus, > 10000 cells") +
  theme_bw() +
  labs(y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(legend.position = c(0.14, 0.5),
        legend.background =  element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25))

p5 <- micro %>% 
  filter(group == "Bacillariophyta" & count > 10000 & !is.na(genus) &
           date > "2020-01-01" &
           date < "2020-12-31") %>% 
  group_by(date, genus) %>% 
  summarise(count_sum = sum(count)) %>% 
  ungroup() %>% 
  complete(date, genus) %>% 
  mutate(count_sum = replace_na(count_sum, 0)) %>% 
  ggplot(aes(date, count_sum, fill = genus)) +
  geom_area() +
  scale_x_date(limits = startEnd_5,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  scale_fill_brewer(palette = "Spectral",
                      name = "Genus, > 10000 cells") +
  theme_bw() +
  labs(y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(legend.position = c(0.14, 0.5),
        legend.background =  element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25))

fig_diat <- p1/p2/p3/p4/p5

ggsave(here("figures", "qu39_ts_diatom.png"), fig_diat, width=16, height=15, dpi=300)
```
```{r}
micro_diat <- micro %>% 
  filter(group == "Bacillariophyta" & count > 30000 & !is.na(genus)) %>% 
  group_by(date, genus) %>% 
  summarise(count_sum = sum(count)) %>% 
  ungroup() %>% 
  complete(date, genus) %>% 
  arrange(date, count_sum)

micro_diat %>% 
  mutate(julian = lubridate::yday(date),
         year = lubridate::year(date)) %>% 
  ggplot(aes(julian, count_sum, fill = genus)) +
  geom_bar(position = "stack", stat = "identity", color = "black", width = 3) +
  scale_fill_brewer(palette = "Spectral") +
  # scale_x_date(limits = startEnd,
  #              breaks = scales::date_breaks("3 month"),
  #              labels = scales::date_format("%m-%y")) +
  facet_wrap(~ year, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 11),
        strip.background = element_blank(),
        strip.text = element_blank()) + 
  labs(x = "Month",
       y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25)) 


ggsave(here("figures", "qu39_ts_diatom_julian.png"), width=16, height=15, dpi=300)





```



